apiVersion: v1
kind: Service
metadata:
    name: backend-api-service
spec:
    type: NodePort
    selector:
      app: backend-api
    ports:
      - nodePort: 30500
        port: 8080
        targetPort: 8080